In [1]:
import pandas as pd

In [2]:
import numpy as np
import itertools
import re
import ordered_set
from ordered_set import OrderedSet

In [3]:
class itemset:
    def __init__(self, items, support):
        self.items = items
        self.support = support
        
    def to_string(self):
        return "Items:" + str(self.items) + "\n Support:" + str(self.support)

In [4]:
class Rules:
    def __init__(self, x, y):
        self.x=x
        self.y=y
    
    def support_count(self, l, df):
        ls=[]
        for se in sorted(l):
            f_df = df[se]
            if(isinstance(f_df, pd.Series)):
                ls.append(itemset(OrderedSet([se]), (sum(f_df))/len(df)))
            else:
                ls.append(itemset(se, sum(f_df.all(axis=1))/len(df)))
        return ls
        
    def confidence_x(self, df):
        
        xs=(self.x[0])
        ys=(self.y[0])
        return (self.support_count([xs | ys], df)[0].support) /(self.support_count(self.x, df)[0].support)
    
    def confidence_y(self, df):
        
        xs=(self.x[0])
        ys=(self.y[0])
        return (self.support_count([xs | ys], df)[0].support) /(self.support_count(self.y,df)[0].support)

In [5]:
class Apriori:
    
    def __init__(self, df):
        self.df = df
        
    def support_count(self, l):
        ls=[]
        for se in sorted(l):
            f_df = self.df[se]
            
            if(isinstance(f_df, pd.Series)):
                ls.append(itemset(OrderedSet([se]), sum(f_df)/len(self.df)))
            else:
                ls.append(itemset(se, (sum(f_df.all(axis=1))/len(self.df))))
        return ls
    
    def create_k_set(self,iters, k):
        ls = []
        for i in range(len(iters)):
            for j in range(len(iters) -1) :
                s1 = iters[i].items
                s2 = iters[j+1].items
                if (s1 != s2 and s1[0:k-2] == s2[0:k-2]) and (len(s1) ==  len(s2)):
                    s = s1 | s2
                    s = sorted(s)
                    s = OrderedSet(s)
                    if s not in ls:
                        ls.append(s)
        return ls
    
    def filter_minsup(self, ls, minsup):
        new_ls = []
        stop_algo = True
        for items in ls:
            if(items.support >= minsup):
                new_ls.append(items)
                if items.support != minsup:
                    stop_algo = False
        return new_ls, stop_algo
    
    def create_x(self, k2, i):     
        xs = {}
        idx =0 
        while(i> 1):
            for xa in k2:
                if i > 1:
                    xs[idx] = list(itertools.combinations(xa.items, i))
                    idx+=1
            i-=1
        return xs
    
    def create_y(self, k2, xs):
        ys = {}
        for idx, itemx in xs.items():
            temp_y = []
            all_items= set(list(itertools.chain(*itemx)))
            for yi in range(len(itemx)):
                y = OrderedSet(itemx[yi]).symmetric_difference(all_items)
                temp_y.append(y)
            ys[idx] = temp_y
        return ys
        
    def create_rules(self, k2, k):
        xs = self.create_x(k2, k)
        ys = self.create_y(k2, xs)
        
        rs = []
        for idx, item in  xs.items():
            for i in range(len(item)):
                yi = ys[idx][i]
                xi = item[i]
                rs.append(Rules([OrderedSet(xi)], [(yi)]))
        
        return rs
        
    
    def apriori(self, minssup):
        k_set=list(self.df.columns)
        k=2
        l_k_set = 0
        while True:
            ck_set = self.support_count(k_set) #should return if tk_set never has an item
            t_k_set, stop_algo = self.filter_minsup(ck_set, minssup)
            if stop_algo: break
            k_set = self.create_k_set(t_k_set, k)
            if len(k_set) == 0: break
            k+=1
            l_k_set+=1
        final_k_set = t_k_set if len(t_k_set) > 0 else k_set
        return self.create_rules(final_k_set, l_k_set)

In [6]:
data = {"customer_id": [1,1,2,2,3,3,4,4,5], "transaction_id": [1,2,3,4,5,6,7,8,9], 
        "items": [["Milk", "Bread", "Butter"], ["Bread", "Cheese"], ["Bread", "Jam"],
                  ["Milk", "Bread", "Cheese"], ["Milk", "Jam"], ["Bread", "Jam"], ["Milk", "Jam"], 
                  ["Milk", "Bread", "Jam", "Butter"], ["Milk", "Bread", "Jam"]]}

In [7]:
df=pd.DataFrame(data)

In [8]:
df

   customer_id  transaction_id                       items
0            1               1       [Milk, Bread, Butter]
1            1               2             [Bread, Cheese]
2            2               3                [Bread, Jam]
3            2               4       [Milk, Bread, Cheese]
4            3               5                 [Milk, Jam]
5            3               6                [Bread, Jam]
6            4               7                 [Milk, Jam]
7            4               8  [Milk, Bread, Jam, Butter]
8            5               9          [Milk, Bread, Jam]

In [9]:
#Index - pass lis
df = df[['transaction_id', 'items']]

In [10]:
df

   transaction_id                       items
0               1       [Milk, Bread, Butter]
1               2             [Bread, Cheese]
2               3                [Bread, Jam]
3               4       [Milk, Bread, Cheese]
4               5                 [Milk, Jam]
5               6                [Bread, Jam]
6               7                 [Milk, Jam]
7               8  [Milk, Bread, Jam, Butter]
8               9          [Milk, Bread, Jam]

In [11]:
for idx, row in df.iterrows():
    for item in row['items']:
        df.loc[idx, item] = True

In [13]:
df.fillna(False, inplace=True)

In [14]:
df.drop('items', axis=1, inplace=True)
df.set_index(['transaction_id'], inplace=True)

In [15]:
df.columns

Index(['Milk', 'Bread', 'Butter', 'Cheese', 'Jam'], dtype='object')

In [16]:
df

                 Milk  Bread  Butter  Cheese    Jam
transaction_id
1                True   True    True   False  False
2               False   True   False    True  False
3               False   True   False   False   True
4                True   True   False    True  False
5                True  False   False   False   True
6               False   True   False   False   True
7                True  False   False   False   True
8                True   True    True   False   True
9                True   True   False   False   True

In [17]:
apriori_df = Apriori(df)

In [19]:
rules = apriori_df.apriori(2/9)

In [20]:
for r in rules:
    print(str(r.y) + " -> " + str(r.x) + str(r.confidence_y(df)))
print("=======")
for r in rules:
    print(str(r.x) + " -> " + str(r.y) + str(r.confidence_x(df)))

[OrderedSet(['Milk'])] -> [OrderedSet(['Bread', 'Butter'])]0.3333333333333333
[OrderedSet(['Butter'])] -> [OrderedSet(['Bread', 'Milk'])]1.0
[OrderedSet(['Bread'])] -> [OrderedSet(['Butter', 'Milk'])]0.2857142857142857
[OrderedSet(['Milk'])] -> [OrderedSet(['Bread', 'Jam'])]0.3333333333333333
[OrderedSet(['Jam'])] -> [OrderedSet(['Bread', 'Milk'])]0.3333333333333333
[OrderedSet(['Bread'])] -> [OrderedSet(['Jam', 'Milk'])]0.2857142857142857
=======
[OrderedSet(['Bread', 'Butter'])] -> [OrderedSet(['Milk'])]1.0
[OrderedSet(['Bread', 'Milk'])] -> [OrderedSet(['Butter'])]0.5
[OrderedSet(['Butter', 'Milk'])] -> [OrderedSet(['Bread'])]1.0
[OrderedSet(['Bread', 'Jam'])] -> [OrderedSet(['Milk'])]0.5
[OrderedSet(['Bread', 'Milk'])] -> [OrderedSet(['Jam'])]0.5
[OrderedSet(['Jam', 'Milk'])] -> [OrderedSet(['Bread'])]0.5

In [22]:
from mlxtend.frequent_patterns import apriori

In [24]:
shop_frequent_itemsets = apriori(df, min_support=2/9, use_colnames=True)

In [25]:
shop_frequent_itemsets

     support               itemsets
0   0.666667                 (Milk)
1   0.777778                (Bread)
2   0.222222               (Butter)
3   0.222222               (Cheese)
4   0.666667                  (Jam)
5   0.444444          (Bread, Milk)
6   0.222222         (Milk, Butter)
7   0.444444            (Milk, Jam)
8   0.222222        (Bread, Butter)
9   0.222222        (Bread, Cheese)
10  0.444444           (Bread, Jam)
11  0.222222  (Bread, Milk, Butter)
12  0.222222     (Bread, Milk, Jam)

In [27]:
from mlxtend.frequent_patterns import association_rules

In [28]:
shop_rules = association_rules(shop_frequent_itemsets, metric="confidence", min_threshold=0.2)

In [29]:
shop_rules[['antecedents', 'consequents', 'confidence']].tail(12)

        antecedents      consequents  confidence
12    (Bread, Milk)         (Butter)    0.500000
13  (Bread, Butter)           (Milk)    1.000000
14   (Milk, Butter)          (Bread)    1.000000
15          (Bread)   (Milk, Butter)    0.285714
16           (Milk)  (Bread, Butter)    0.333333
17         (Butter)    (Bread, Milk)    1.000000
18    (Bread, Milk)            (Jam)    0.500000
19     (Bread, Jam)           (Milk)    0.500000
20      (Milk, Jam)          (Bread)    0.500000
21          (Bread)      (Milk, Jam)    0.285714
22           (Milk)     (Bread, Jam)    0.333333
23            (Jam)    (Bread, Milk)    0.333333

In [30]:
df=pd.read_csv("tutorial3")
df.head(20)

        A  Quantity  Transaction  Store         Product
0   30000         2        93194      6        Magazine
1   30001         2        93194      6       Candy Bar
2   30002         2        93194      6       Candy Bar
3   30003         2        93194      6       Candy Bar
4   30004         2        93194      6       Candy Bar
5   30005         2        93197      1         Pencils
6   30006         1        93200      6       Candy Bar
7   30007         1        93200      6       Candy Bar
8   30008         1        93200      6       Candy Bar
9   30009         1        93200      6        Magazine
10  30010         1        93206      8        Magazine
11  30011         1        93206      8  Greeting Cards
12  30012         1        93206      8         Pencils
13  30013         1        93206      8         Pencils
14  30014         5        93212      4      Toothbrush
15  30015         1        93215      4       Candy Bar
16  30016         1        93215      4       Candy Bar
17  30017         1        93215      4  Greeting Cards
18  30018         8        93233      7      Toothbrush
19  30019         1        93239      5        Magazine

In [31]:
df2 = df.groupby(["Transaction", "Product"]).size().reset_index(name="Count")
df2.head(20)

    Transaction         Product  Count
0         93194       Candy Bar      4
1         93194        Magazine      1
2         93197         Pencils      1
3         93200       Candy Bar      3
4         93200        Magazine      1
5         93206  Greeting Cards      1
6         93206        Magazine      1
7         93206         Pencils      2
8         93212      Toothbrush      1
9         93215       Candy Bar      2
10        93215  Greeting Cards      1
11        93233      Toothbrush      1
12        93239        Magazine      1
13        93245       Candy Bar      1
14        93248       Candy Bar      1
15        93251        Magazine      2
16        93257        Magazine      1
17        93260        Magazine      1
18        93263        Magazine     16
19        93272       Candy Bar      1

In [32]:
df3 = (df2.groupby(["Transaction", "Product"])['Count']
          .sum().unstack().reset_index().fillna(0)
          .set_index('Transaction'))

df3.head()

Product,Bow,Candy Bar,Deodorant,Greeting Cards,Magazine,Markers,Pain Reliever,Pencils,Pens,Perfume,Photo Processing,Prescription Med,Shampoo,Soap,Toothbrush,Toothpaste,Wrapping Paper
Transaction,,,,,,,,,,,,,,,,,
93194,0.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93200,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93206,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93212,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [33]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

df4 = df3.applymap(encode_units)

df4

Product,Bow,Candy Bar,Deodorant,Greeting Cards,Magazine,Markers,Pain Reliever,Pencils,Pens,Perfume,Photo Processing,Prescription Med,Shampoo,Soap,Toothbrush,Toothpaste,Wrapping Paper
Transaction,,,,,,,,,,,,,,,,,
93194,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
93197,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
93200,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
93206,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0
93212,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133406,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
133424,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133427,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
133430,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
133433,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0

In [34]:
app = Apriori(df4)

In [35]:
app.df

Product,Bow,Candy Bar,Deodorant,Greeting Cards,Magazine,Markers,Pain Reliever,Pencils,Pens,Perfume,Photo Processing,Prescription Med,Shampoo,Soap,Toothbrush,Toothpaste,Wrapping Paper
Transaction,,,,,,,,,,,,,,,,,
93194,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
93197,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
93200,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
93206,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0
93212,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133406,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
133424,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133427,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
133430,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
133433,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0

In [36]:
tx = app.apriori(0.001)

In [37]:
for r in tx:
    print(str(r.y) + " -> " + str(r.x) + str(r.confidence_y(df4)))
print("=======")
for r in tx:
    print(str(r.x) + " -> " + str(r.y) + str(r.confidence_x(df4)))

[OrderedSet(['Toothpaste'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Perfume', 'Toothbrush'])]0.0036596523330283625
[OrderedSet(['Toothbrush'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Perfume', 'Toothpaste'])]0.00879120879120879
[OrderedSet(['Perfume'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Toothbrush', 'Toothpaste'])]0.007194244604316546
[OrderedSet(['Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume', 'Toothbrush', 'Toothpaste'])]0.002564102564102564
[OrderedSet(['Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Perfume', 'Toothbrush', 'Toothpaste'])]0.003891050583657587
[OrderedSet(['Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Perfume', 'Toothbrush', 'Toothpaste'])]0.0033840947546531297
[OrderedSet(['Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Perfume'])]0.16666666666666666
[OrderedSet(['Perfume', 'Toothpaste'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Toothbrush'])]0.1212121212121212
[OrderedSet(['Toothbrush', 'Perfume'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Toothpaste'])]0.03478260869565217
[OrderedSet(['Toothpaste', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume', 'Toothbrush'])]0.01990049751243781
[OrderedSet(['Toothbrush', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume', 'Toothpaste'])]0.05263157894736842
[OrderedSet(['Perfume', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Toothbrush', 'Toothpaste'])]0.0425531914893617
[OrderedSet(['Toothpaste', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Perfume', 'Toothbrush'])]0.017857142857142856
[OrderedSet(['Toothbrush', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Perfume', 'Toothpaste'])]0.2222222222222222
[OrderedSet(['Perfume', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Toothbrush', 'Toothpaste'])]0.16666666666666666
[OrderedSet(['Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Perfume', 'Toothbrush', 'Toothpaste'])]0.015873015873015872
[OrderedSet(['Toothpaste', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Perfume', 'Toothbrush'])]0.014336917562724013
[OrderedSet(['Toothbrush', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Perfume', 'Toothpaste'])]0.14814814814814814
[OrderedSet(['Perfume', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Toothbrush', 'Toothpaste'])]0.11428571428571428
[OrderedSet(['Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Perfume', 'Toothbrush', 'Toothpaste'])]0.014869888475836429
[OrderedSet(['Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Perfume', 'Toothbrush', 'Toothpaste'])]0.012903225806451613
[OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine'])]0.5
[OrderedSet(['Toothbrush', 'Toothpaste', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume'])]0.3333333333333333
[OrderedSet(['Perfume', 'Toothpaste', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Toothbrush'])]0.19047619047619047
[OrderedSet(['Toothbrush', 'Perfume', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards', 'Toothpaste'])]0.14285714285714285
[OrderedSet(['Toothbrush', 'Toothpaste', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Perfume'])]0.5
[OrderedSet(['Perfume', 'Toothpaste', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Toothbrush'])]0.39999999999999997
[OrderedSet(['Toothbrush', 'Perfume', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine', 'Toothpaste'])]0.4444444444444444
[OrderedSet(['Toothpaste', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Perfume', 'Toothbrush'])]0.05333333333333333
[OrderedSet(['Toothbrush', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Perfume', 'Toothpaste'])]0.3636363636363636
[OrderedSet(['Perfume', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Toothbrush', 'Toothpaste'])]0.25
[OrderedSet(['Toothbrush', 'Toothpaste', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Perfume'])]0.39999999999999997
[OrderedSet(['Perfume', 'Toothpaste', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Toothbrush'])]0.2857142857142857
[OrderedSet(['Toothbrush', 'Perfume', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Toothpaste'])]0.39999999999999997
[OrderedSet(['Toothpaste', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Perfume', 'Toothbrush'])]0.0449438202247191
[OrderedSet(['Toothbrush', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Perfume', 'Toothpaste'])]0.2857142857142857
[OrderedSet(['Perfume', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Toothbrush', 'Toothpaste'])]0.19999999999999998
[OrderedSet(['Toothpaste', 'Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Perfume', 'Toothbrush'])]0.04081632653061224
[OrderedSet(['Toothbrush', 'Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Perfume', 'Toothpaste'])]0.3636363636363636
[OrderedSet(['Perfume', 'Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Toothbrush', 'Toothpaste'])]0.25
[OrderedSet(['Greeting Cards', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Perfume', 'Toothbrush', 'Toothpaste'])]0.03448275862068965
[OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Greeting Cards'])]0.7999999999999999
[OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste', 'Greeting Cards'])] -> [OrderedSet(['Candy Bar', 'Magazine'])]1.0
[OrderedSet(['Toothbrush', 'Toothpaste', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Perfume'])]0.6666666666666666
[OrderedSet(['Perfume', 'Toothpaste', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Toothbrush'])]0.4444444444444444
[OrderedSet(['Toothbrush', 'Perfume', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Candy Bar', 'Toothpaste'])]0.5714285714285714
[OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Magazine'])]1.0
[OrderedSet(['Toothbrush', 'Toothpaste', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Perfume'])]0.5714285714285714
[OrderedSet(['Perfume', 'Toothpaste', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Toothbrush'])]0.3333333333333333
[OrderedSet(['Toothbrush', 'Perfume', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Greeting Cards', 'Toothpaste'])]0.5
[OrderedSet(['Toothbrush', 'Toothpaste', 'Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Perfume'])]0.6666666666666666
[OrderedSet(['Perfume', 'Toothpaste', 'Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Toothbrush'])]0.39999999999999997
[OrderedSet(['Toothbrush', 'Perfume', 'Greeting Cards', 'Candy Bar'])] -> [OrderedSet(['Magazine', 'Toothpaste'])]0.5714285714285714
[OrderedSet(['Toothpaste', 'Greeting Cards', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Perfume', 'Toothbrush'])]0.10256410256410256
[OrderedSet(['Toothbrush', 'Greeting Cards', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Perfume', 'Toothpaste'])]0.5714285714285714
[OrderedSet(['Perfume', 'Greeting Cards', 'Magazine', 'Candy Bar'])] -> [OrderedSet(['Toothbrush', 'Toothpaste'])]0.30769230769230765
=======
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste'])]0.5714285714285714
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush'])]0.4444444444444444
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume'])]1.0
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Magazine'])]1.0
[OrderedSet(['Candy Bar', 'Magazine', 'Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Greeting Cards'])]1.0
[OrderedSet(['Greeting Cards', 'Magazine', 'Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Candy Bar'])]1.0
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste'])]0.30769230769230765
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste'])]0.5714285714285714
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume'])]0.10256410256410256
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Magazine'])]0.5714285714285714
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Magazine'])]0.39999999999999997
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Magazine'])]0.6666666666666666
[OrderedSet(['Candy Bar', 'Magazine', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Greeting Cards'])]0.5
[OrderedSet(['Candy Bar', 'Magazine', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Greeting Cards'])]0.3333333333333333
[OrderedSet(['Candy Bar', 'Magazine', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Greeting Cards'])]0.5714285714285714
[OrderedSet(['Candy Bar', 'Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Greeting Cards', 'Magazine'])]1.0
[OrderedSet(['Greeting Cards', 'Magazine', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Candy Bar'])]0.5714285714285714
[OrderedSet(['Greeting Cards', 'Magazine', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Candy Bar'])]0.4444444444444444
[OrderedSet(['Greeting Cards', 'Magazine', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Candy Bar'])]0.6666666666666666
[OrderedSet(['Greeting Cards', 'Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Magazine', 'Candy Bar'])]1.0
[OrderedSet(['Magazine', 'Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Greeting Cards', 'Candy Bar'])]0.7999999999999999
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Magazine'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste'])]0.03448275862068965
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste', 'Magazine'])]0.25
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste', 'Magazine'])]0.3636363636363636
[OrderedSet(['Candy Bar', 'Greeting Cards', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Magazine'])]0.04081632653061224
[OrderedSet(['Candy Bar', 'Magazine', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste', 'Greeting Cards'])]0.19999999999999998
[OrderedSet(['Candy Bar', 'Magazine', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste', 'Greeting Cards'])]0.2857142857142857
[OrderedSet(['Candy Bar', 'Magazine', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Greeting Cards'])]0.0449438202247191
[OrderedSet(['Candy Bar', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Greeting Cards', 'Magazine'])]0.39999999999999997
[OrderedSet(['Candy Bar', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Greeting Cards', 'Magazine'])]0.2857142857142857
[OrderedSet(['Candy Bar', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Greeting Cards', 'Magazine'])]0.39999999999999997
[OrderedSet(['Greeting Cards', 'Magazine', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste', 'Candy Bar'])]0.25
[OrderedSet(['Greeting Cards', 'Magazine', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste', 'Candy Bar'])]0.3636363636363636
[OrderedSet(['Greeting Cards', 'Magazine', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Candy Bar'])]0.05333333333333333
[OrderedSet(['Greeting Cards', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Magazine', 'Candy Bar'])]0.4444444444444444
[OrderedSet(['Greeting Cards', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Magazine', 'Candy Bar'])]0.39999999999999997
[OrderedSet(['Greeting Cards', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Magazine', 'Candy Bar'])]0.5
[OrderedSet(['Magazine', 'Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Greeting Cards', 'Candy Bar'])]0.14285714285714285
[OrderedSet(['Magazine', 'Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Greeting Cards', 'Candy Bar'])]0.19047619047619047
[OrderedSet(['Magazine', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Greeting Cards', 'Candy Bar'])]0.3333333333333333
[OrderedSet(['Perfume', 'Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Greeting Cards', 'Magazine', 'Candy Bar'])]0.5
[OrderedSet(['Candy Bar', 'Greeting Cards'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste', 'Magazine'])]0.012903225806451613
[OrderedSet(['Candy Bar', 'Magazine'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste', 'Greeting Cards'])]0.014869888475836429
[OrderedSet(['Candy Bar', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste', 'Greeting Cards', 'Magazine'])]0.11428571428571428
[OrderedSet(['Candy Bar', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste', 'Greeting Cards', 'Magazine'])]0.14814814814814814
[OrderedSet(['Candy Bar', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Greeting Cards', 'Magazine'])]0.014336917562724013
[OrderedSet(['Greeting Cards', 'Magazine'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Toothpaste', 'Candy Bar'])]0.015873015873015872
[OrderedSet(['Greeting Cards', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste', 'Magazine', 'Candy Bar'])]0.16666666666666666
[OrderedSet(['Greeting Cards', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste', 'Magazine', 'Candy Bar'])]0.2222222222222222
[OrderedSet(['Greeting Cards', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Magazine', 'Candy Bar'])]0.017857142857142856
[OrderedSet(['Magazine', 'Perfume'])] -> [OrderedSet(['Toothbrush', 'Toothpaste', 'Greeting Cards', 'Candy Bar'])]0.0425531914893617
[OrderedSet(['Magazine', 'Toothbrush'])] -> [OrderedSet(['Perfume', 'Toothpaste', 'Greeting Cards', 'Candy Bar'])]0.05263157894736842
[OrderedSet(['Magazine', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Perfume', 'Greeting Cards', 'Candy Bar'])]0.01990049751243781
[OrderedSet(['Perfume', 'Toothbrush'])] -> [OrderedSet(['Toothpaste', 'Greeting Cards', 'Magazine', 'Candy Bar'])]0.03478260869565217
[OrderedSet(['Perfume', 'Toothpaste'])] -> [OrderedSet(['Toothbrush', 'Greeting Cards', 'Magazine', 'Candy Bar'])]0.1212121212121212
[OrderedSet(['Toothbrush', 'Toothpaste'])] -> [OrderedSet(['Perfume', 'Greeting Cards', 'Magazine', 'Candy Bar'])]0.16666666666666666

In [42]:
pd.set_option('display.max_colwidth', 400)

In [43]:
shop_frequent_itemsets = apriori(df4, min_support=0.001, use_colnames=True)

(shop_frequent_itemsets.head(500).tail(50))

      support                                                    itemsets
166  0.001041                                (Magazine, Shampoo, Perfume)
167  0.004163                             (Magazine, Toothbrush, Perfume)
168  0.003122                             (Magazine, Toothpaste, Perfume)
169  0.001041                       (Magazine, Shampoo, Photo Processing)
170  0.001487                    (Magazine, Toothbrush, Photo Processing)
171  0.002230                    (Magazine, Toothpaste, Photo Processing)
172  0.001041                (Magazine, Wrapping Paper, Photo Processing)
173  0.001635                (Magazine, Prescription Med, Wrapping Paper)
174  0.002230                             (Magazine, Toothbrush, Shampoo)
175  0.001189                             (Magazine, Toothpaste, Shampoo)
176  0.001189                                (Magazine, Toothbrush, Soap)
177  0.001189                                (Magazine, Toothpaste, Soap)
178  0.001784                          (Magazine, Toothbrush, Toothpaste)
179  0.001041                      (Magazine, Toothbrush, Wrapping Paper)
180  0.001041                      (Magazine, Toothpaste, Wrapping Paper)
181  0.001338                                 (Pencils, Toothpaste, Pens)
182  0.001041                     (Pencils, Toothpaste, Photo Processing)
183  0.001041                                 (Toothbrush, Perfume, Pens)
184  0.001041                                 (Shampoo, Toothbrush, Pens)
185  0.001041                              (Toothbrush, Toothpaste, Pens)
186  0.001041                     (Toothpaste, Perfume, Photo Processing)
187  0.001338                              (Shampoo, Toothbrush, Perfume)
188  0.001189                           (Toothpaste, Toothbrush, Perfume)
189  0.001041                           (Shampoo, Toothbrush, Toothpaste)
190  0.004906              (Magazine, Candy Bar, Pencils, Greeting Cards)
191  0.002230                 (Magazine, Candy Bar, Pens, Greeting Cards)
192  0.001933              (Magazine, Candy Bar, Perfume, Greeting Cards)
193  0.002081     (Magazine, Greeting Cards, Candy Bar, Photo Processing)
194  0.001041                 (Magazine, Candy Bar, Soap, Greeting Cards)
195  0.001041           (Magazine, Candy Bar, Toothbrush, Greeting Cards)
196  0.005798           (Magazine, Candy Bar, Toothpaste, Greeting Cards)
197  0.003568            (Candy Bar, Pencils, Toothpaste, Greeting Cards)
198  0.001784               (Candy Bar, Toothpaste, Pens, Greeting Cards)
199  0.001041            (Candy Bar, Perfume, Greeting Cards, Toothbrush)
200  0.001487            (Toothpaste, Candy Bar, Perfume, Greeting Cards)
201  0.003420                  (Magazine, Candy Bar, Pencils, Toothpaste)
202  0.002081                     (Magazine, Candy Bar, Toothpaste, Pens)
203  0.001189                  (Magazine, Candy Bar, Perfume, Toothbrush)
204  0.001784                  (Magazine, Candy Bar, Perfume, Toothpaste)
205  0.001041                  (Magazine, Candy Bar, Shampoo, Toothpaste)
206  0.001041               (Magazine, Candy Bar, Toothbrush, Toothpaste)
207  0.001041                   (Magazine, Pencils, Pens, Greeting Cards)
208  0.002825             (Magazine, Pencils, Toothpaste, Greeting Cards)
209  0.001635                (Magazine, Toothpaste, Pens, Greeting Cards)
210  0.001041             (Magazine, Toothbrush, Perfume, Greeting Cards)
211  0.001338             (Magazine, Toothpaste, Perfume, Greeting Cards)
212  0.001041    (Magazine, Greeting Cards, Toothpaste, Photo Processing)
213  0.001784  (Toothpaste, Greeting Cards, Magazine, Candy Bar, Pencils)
214  0.001041  (Toothbrush, Perfume, Greeting Cards, Magazine, Candy Bar)
215  0.001338  (Perfume, Toothpaste, Greeting Cards, Magazine, Candy Bar)

In [44]:
# Finding the association rules
shop_rules = association_rules(shop_frequent_itemsets, metric="confidence", min_threshold=0.00001)


# Sorting 
shop_rules.sort_values("confidence", ascending = False, inplace = True)

# Previewing the associative rules 


#top 10 combinations of items frequently bought together
shop_rules.head(10000).tail(900).head(700).tail(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
788,(Toothbrush),"(Magazine, Candy Bar, Greeting Cards)",0.067648,0.017247,0.001041,0.015385,0.892042,-0.000126,0.998109
553,(Magazine),"(Toothpaste, Pens)",0.231936,0.007731,0.003420,0.014744,1.907027,0.001626,1.007117
870,(Magazine),"(Candy Bar, Pencils, Toothpaste)",0.231936,0.011002,0.003420,0.014744,1.340073,0.000868,1.003797
733,(Greeting Cards),"(Magazine, Candy Bar, Pens)",0.152840,0.004758,0.002230,0.014591,3.066938,0.001503,1.009979
887,(Pens),"(Magazine, Candy Bar, Toothpaste)",0.144068,0.013232,0.002081,0.014448,1.091870,0.000175,1.001233
339,(Pens),"(Candy Bar, Pencils)",0.144068,0.035088,0.002081,0.014448,0.411765,-0.002974,0.979058
212,(Perfume),"(Toothbrush, Bow)",0.082664,0.010110,0.001189,0.014388,1.423191,0.000354,1.004341
699,(Perfume),"(Toothbrush, Toothpaste)",0.082664,0.003568,0.001189,0.014388,4.032374,0.000894,1.010978
900,(Perfume),"(Magazine, Candy Bar, Toothbrush)",0.082664,0.002081,0.001189,0.014388,6.912641,0.001017,1.012487
18,(Toothpaste),(Bow),0.162504,0.051591,0.002230,0.013724,0.266010,-0.006154,0.961606